#!/bin/bash

## TODO: Ensure that images are present in ~/temp-data/web-data/

# delete any exiting gh-pages branch
git branch -D gh-pages
git push origin --delete gh-pages

git checkout --orphan gh-pages

# remove extra files not needed by the website
git rm -r src --force
rm -rf src
git rm -r docs --force
git rm -r osm-data --force
git rm -r scripts --force
git rm 'README.md' --force
echo Try "[matiasdahl.github.io/osm-tag-dynamics/](http://matiasdahl.github.io/osm-tag-dynamics/)" > README.md
git add README.md

cp ~/temp-data/web-data/am_data.txt .
git add am_data.txt

mkdir images
cp ~/temp-data/web-data/images/*.svg images
git add images/*.svg

git mv web-site/index.html .
git mv web-site/main.js .
git mv web-site/style.css .
git rm -r web-site --force
rm -rf web-site

## Add tracking code
sed -e 's|<!-- tracking code -->|<!-- tracking code --><img src="http://explorecolor.com/piwik/piwik.php?idsite=3&rec=1" style="border:0" alt="" />|g' < index.html > index2.html
mv index2.html index.html
git add index.html

git commit -m "Update of gh-pages"
git push origin gh-pages
git checkout master
